### ISSUE TITLE
2 Samuel 7:12 listed twice in LXX data

### ISSUE THREAD

**Issue by fhightower** [parabible/parabible-server#2]
The data for the LXX has 2 Samuel 7:12 listed twice (https://parabible.com/2-Samuel/7). I've tried to find the offending line in the [verse_data.json](https://github.com/parabible/parabible-server/blob/master/data/verse_data.json) file, but it's so large I haven't been able to work with it. I was, however, able to capture the response when the LXX for 2 Samuel 7 is loaded in my browser and have attached that here: [2sam_7.txt](https://github.com/parabible/parabible-server/files/1603354/2sam_7.txt). If you download it and search for "2Sam 7:12", you can see that it is listed twice.

P.S. Thanks for creating parabible! I recently found it and love using it for research.

**Comment by jcuenod** [comment]
Thanks very much!
I know there are still some LXX issues (and I actually still need to import some of the word data). I'll take a look at this.

**Comment by jcuenod** [comment]
Okay, the reason that this is happening is not to do with verse_data.json. It's how I'm importing data.
Lining up the LXX verses with BHS is not as straightforward as would be nice and maybe (no, definitely) I need to rethink how I'm doing it.

In this case, the CCAT data for the parallels lists `καὶ ἔσται` (LXX v12) as being in parallel with what it apparently believes is a והיה יהוה in v11 of the Hebrew but I'm not able to find that right now.

You can see the original source here: http://ccat.sas.upenn.edu/gopher/text/religion/biblical/parallel/12.2Sam.par

I'm not going to fix this right now because it raises a larger problem of lining up the parallels (and I'm already actually fudging that because I'm using LXXb books that line up better than the A versions from CCAT simply because it reduced my work but the LXX is a bigger problem...)

**Comment by fhightower** [comment]
Gotcha, thanks for looking into it!

**Comment by jcuenod** [comment]
Also, just to follow up a bit further, I'm looking into some more sophisticated parallel techniques right now with https://github.com/Arithmeticus/TAN-bible. I'm not sure what will come of it but it's something I'm exploring... If you have ideas or suggestions (or code) I welcome them...

**Comment by jcuenod** [comment]
Another update: I think the TAN stuff is too much at this point. I am seriously looking into migrating to a simpler model that uses mysql instead of the in-memory json format that I have right now. Part of that migration will mean a change from Mongo and so a new way of lining up texts. I think I will probably remove this kind of duplication if and when I do that.

**Comment by jcuenod** [comment]
Hey @fhightower,

I just thought I'd let you know that I've been building the successor to the production version of parabible in the background for some time. It's still a bit of a mess, but I'm inching closer to something that can be more collectively contributed to. I have the LXX pipeline building [here](https://github.com/jcuenod/parabible-data-pipeline/tree/master/gk-stead-ccat-pipe), for example (though the data pipeline, particularly my work on alignment is not at all cleaned up or even version controlled yet). It does resolve the problem, though (especially thanks to this issue, I decided to only ever allow a single verse to be parallel to another single verse). You can see it at dev.parabible.com (my unstable staging environment—I try to keep it up but make no guarantees).

I've been starting to push things to https://github.com/parabible/ (like [parabible-server-2](https://github.com/parabible/parabible-server-2)). And I've been starting to document the [API](https://github.com/parabible/parabible-server-2/wiki) as well.

Thanks for your interest and taking enough of a look to file a thought through issue! I'm going to close this issue as the way forward is pretty clear and its resolved in the new version.

Cheerio,
James
